"use client";

export default function Disclaimer() {
  return (
    <div className="space-y-2">
      <p className="text-[11px] text-bark-600 leading-relaxed">
        <strong className="text-bark-500">Informational Only.</strong> This application does not
        provide medical advice, diagnosis, or treatment. Predicted experiences are generated by a
        simplified heuristic model and do not represent clinical or pharmacological outcomes.
        Individual experiences vary widely based on tolerance, biology, consumption method, dosage,
        and many other factors.
      </p>
      <p className="text-[11px] text-bark-600 leading-relaxed">
        <strong className="text-bark-500">Legality.</strong> Cannabis legality varies by
        jurisdiction. It is your responsibility to comply with applicable local, state, and federal
        laws. This tool makes no representation about the legality of any substance in your area.
      </p>
      <p className="text-[11px] text-bark-600 leading-relaxed">
        <strong className="text-bark-500">Start Low, Go Slow.</strong> If you choose to consume
        cannabis, start with a low dose and wait to understand its effects before consuming more.
        Never drive or operate heavy machinery under the influence. Consult a healthcare provider
        with any health-related questions.
      </p>
    </div>
  );
}
